name: Recovery Build Final
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparation
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip
          curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          chmod a+x /usr/local/bin/repo

      - name: Build
        run: |
          # ... (начало как обычно) ...
          source build/envsetup.sh
          lunch twrp_RMX3938-eng
          
          # ОЧИСТКА, чтобы заставить Ninja работать
          make clean
          
          # Сборка
          make recoveryimage -j$(nproc --all)
          
          # Поиск вообще любого .img файла на сервере
          mkdir -p ../COLLECTION
          find out/ -name "*.img" -size +10M -exec cp {} ../COLLECTION/ \;

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FINAL_CHANCE_FILES
          path: COLLECTION/
