name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup
      run: |
        docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /opt/ghc
        sudo apt-get clean

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib mingw-w64-i686-dev libxml2-utils xsltproc gperf

    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync TWRP Sources
      run: |
        mkdir /home/runner/twrp
        cd /home/runner
