name: Recovery Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Recovery
        uses: SebaUbuntu/Action-Recovery-Builder@main
        with:
          recipe: 'twrp'
          repo: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'
          branch: 'twrp-12.1'
          device: 'ussi_arm64'
          vendor: 'unisoc'
          path: '.'
