name: TWRP Builder Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare System
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          # Мы убрали lib32ncurses5-dev и заменили на то, что точно есть
          sudo apt-get install -y git curl bc build-essential zip unzip libncurses5 libncurses5:i386 libstdc++6:i386

      - name: Sync Test
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Builder"
          # Ставим инструмент repo вручную, чтобы не зависеть от пакетов
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=$PATH:~/bin
          
          echo "Connecting to TWRP source..."
          ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1 --depth=1
          echo "Success! System is ready for full build."
