name: Extract Boot with Magiskboot

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          sudo apt update && sudo apt install -y cpio
          chmod +x magiskboot

      - name: Unpack Boot
        run: |
          ./magiskboot unpack boot.img
          ls -R
          tar -cvzf boot_extracted.tar.gz *

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: boot-contents-final
          path: boot_extracted.tar.gz
          if-no-files-found: warn
